// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXpy5Elf0nNS3qfR5sQwfZZl9iBYE0rrs',
    appId: '1:862564551805:web:c34b495bc9092bbbc1b514',
    messagingSenderId: '862564551805',
    projectId: 'acme-corp-b9cd5',
    authDomain: 'acme-corp-b9cd5.firebaseapp.com',
    storageBucket: 'acme-corp-b9cd5.appspot.com',
    measurementId: 'G-9LQVJQK62V',
    databaseURL:
        'https://acme-corp-b9cd5-default-rtdb.europe-west1.firebasedatabase.app/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCys4tPHhnkacG9q9XDq1K-xFXI1vBkBsA',
    appId: '1:862564551805:android:810d6c7367c56ba3c1b514',
    messagingSenderId: '862564551805',
    projectId: 'acme-corp-b9cd5',
    storageBucket: 'acme-corp-b9cd5.appspot.com',
    databaseURL:
        'https://acme-corp-b9cd5-default-rtdb.europe-west1.firebasedatabase.app/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQhoGkF0AU0NvqnzxGHn90xgXd6q_7BMM',
    appId: '1:862564551805:ios:d0dd23658854c4c0c1b514',
    messagingSenderId: '862564551805',
    projectId: 'acme-corp-b9cd5',
    storageBucket: 'acme-corp-b9cd5.appspot.com',
    iosClientId:
        '862564551805-3b0hptckvq1pi7p3ntipg2r60248ih53.apps.googleusercontent.com',
    iosBundleId: 'com.example.acmeCorp',
    databaseURL:
        'https://acme-corp-b9cd5-default-rtdb.europe-west1.firebasedatabase.app/',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQhoGkF0AU0NvqnzxGHn90xgXd6q_7BMM',
    appId: '1:862564551805:ios:d0dd23658854c4c0c1b514',
    messagingSenderId: '862564551805',
    projectId: 'acme-corp-b9cd5',
    storageBucket: 'acme-corp-b9cd5.appspot.com',
    iosClientId:
        '862564551805-3b0hptckvq1pi7p3ntipg2r60248ih53.apps.googleusercontent.com',
    iosBundleId: 'com.example.acmeCorp',
    databaseURL:
        'https://acme-corp-b9cd5-default-rtdb.europe-west1.firebasedatabase.app/',
  );
}
